### ISSUE TITLE
Error Output is Not Helpful

### ISSUE THREAD

**Issue by drusellers** [duncansmart/LessCoffee#1]
I am currently getting an error screen which says:

/\* Generated by DotSmart LessCoffee on 11/22/2011 6:58:43 PM - http://dotsmart.net _/ 
/_ Using LESS - Leaner CSS v1.1.3 - http://lesscss.org - Copyright (c) 2010, Alexis Sellier */ 

千牣灩⁴牅潲㩲䰠慯楤杮礠畯⁲敳瑴湩獧映楡敬⹤⠠捁散獳椠⁳敤楮摥‮ഩ

/\* Error in fluent.less:  */
## 

I have no idea why its in chinese - and I have no idea what it means after running through google translate. 

Any help would be appreciated.

-d

**Comment by duncansmart** [comment]
Less.js sometimes errors without outputting the reason. I've just uploaded a new version to nuget that include LESS 1.1.5 - please update to that.

In your case though, this looks like an encoding issue. Any chance you could send the offending file (duncan.smart gmail)?

**Comment by drusellers** [comment]
ok. updated to that and I am still getting the same error. I have set the encoding of all files to UTF-8. any other changes? I will try and track down the offending file.

**Comment by drusellers** [comment]
I am currently getting this with an empty file. :(

**Comment by duncansmart** [comment]
Dru, I saved the "Chinese" message you got in Notepad as unicode txt and opened in a HEX editor and could see the actual error message: 

```
CScript Error: Loading your settings failed. (Access is denied. )
```

Which according to http://www.mvps.org/scripting/faq/wshfaq.htm means:

> ...generally means you either don't have read permissions for HKLM\Software\Microsoft\Windows Script Host\Settings or the equivalent key in HKCU. You need to be able to read both of those to run WSH.

So you might want to check that what whatever AppPool account you're using has those read permissions.

For my part I'm clearly outputting something which is ASCII-encoded but treating as Unicode - which I need to address.

**Comment by drusellers** [comment]
sweet - got the latest version and all is happy - thanks.
