### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by Nettsentrisk** [duncansmart/LessCoffee#4]
Hi, I just cloned the project, and it won't build.

Following errors: 

> Error 1   Cannot find module 'D:\Projects\GitHub\LessCoffee\src\Handlers\nodejs\node_modules\npm\bin\npm-cli.js'  D:\Projects\GitHub\LessCoffee\src\Handlers\EXEC LessCoffee
> 
> Error 2   The command "D:\Projects\GitHub\LessCoffee\src\Handlers\tar-node.cmd" exited with code 1.  LessCoffee
> 
> Error 3   Metadata file 'D:\Projects\GitHub\LessCoffee\src\Handlers\bin\LessCoffee.dll' could not be found    D:\Projects\GitHub\LessCoffee\src\TestWeb\CSC   LessCoffee.TestWeb

Anything I've not understood?

**Comment by duncansmart** [comment]
It's a bit "Works on my Machine" at the moment. I'll update the build script to pull in dependencies later today.

**Comment by Nettsentrisk** [comment]
Great, thanks.

**Comment by duncansmart** [comment]
Should work now. `pre-build.cmd` which is called from the csproj build pulls down node, npm and less and packages them up as a resource.

**Comment by Nettsentrisk** [comment]
Great! I'll test this out later today or tomorrow. :-)
