### ISSUE TITLE
Turn off selector comments added to LESS files?

### ISSUE THREAD

**Issue by Nettsentrisk** [duncansmart/LessCoffee#5]
In the output in the LESS files, I see that it's adding comments above every selector like this:

> /\* line 19, D:\Projects\Project\branches\master\src\Web\Styles\global- */

I'm not sure what the point of these are. To point out which line it corresponds to in what will be the combined bundle file? In any case, it would be nice if this could be turned off, as it's only bloating the LESS files running in debug mode, and not really providing anything needed.

**Comment by duncansmart** [comment]
It's a feature :-) It only does this when `<system.web><compilation debug="true">`. For release builds, when `debug="false"` then you'll get minified output.

**Comment by Nettsentrisk** [comment]
OK, would be great if there was a config option to turn off this (in some cases very useful) feature :)

**Comment by duncansmart** [comment]
Yeah the config option is `<compilation debug="true|false">` :-)

Very useful when hunting down where a style is defined when using Chrome Web Inspector.

![less debug mode](https://f.cloud.github.com/assets/576343/1453016/70aae448-42e5-11e3-8075-801b0096fcea.png)

**Comment by Nettsentrisk** [comment]
Well, in my case I'm using the built-in @Styles.Render method, which outputs each stylesheet from the bundle on its own, in debug mode. So thus I don't need to wonder where the style rule is in which file, since I can see the line and file name directly in the browser inspector.

This is how it looks on my end:

![image](https://f.cloud.github.com/assets/1027492/1453085/1e51ca1a-42e8-11e3-99ae-a312ae3e25ef.png)

![image](https://f.cloud.github.com/assets/1027492/1453090/64ebbb16-42e8-11e3-9760-fc82e65aa06c.png)

As you can see, this feature isn't needed when using the built-in methods in Web.Optimization to render out each stylesheet separately in debug mode :)

**Comment by duncansmart** [comment]
I see. I don't use the Web.Optimization stuff. I have a main.less file that @imports all the others, that way I can override variables easily. e.g.

```
@import "bootstrap/less/bootstrap.less";

// override bootstrap/variables.less
@linkColor: #0064cd;
@headingsFontWeight: normal;
@navbarText: #555;
```
